# Coolify-specific docker-compose.yml
version: '3.8'

services:
  attack-surface-scanner:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "0"
      PYTHONUNBUFFERED: "1"
    volumes:
      - scan_data:/tmp/scans
    restart: unless-stopped

volumes:
  scan_data:
    driver: local